/*
-- Query: SELECT * FROM insurance_db.applications
LIMIT 0, 1000

-- Date: 2017-07-05 12:31
*/
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (3,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','sdmsadjas',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (4,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','pending',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (5,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','approve',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (6,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','approve',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (7,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','approve',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (8,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','approve',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (9,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','approve',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (10,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','approve',NULL);
INSERT INTO `applications` (`applicationId`,`address`,`dateApplied`,`dateAssigned`,`dob`,`education`,`email`,`fieldsFilledIn`,`mobile`,`name`,`occupation`,`policy`,`salary`,`ssn`,`status`,`assignedEmployee_email`) VALUES (12,'8823 broeas eay',NULL,NULL,NULL,NULL,'peace22233@gmail.com',0,'2908813367','peace',NULL,NULL,0,'323115553','pending',NULL);
